//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.DotNet.UpgradeAssistant.Extensions.Default.Analyzers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.DotNet.UpgradeAssistant.Extensions.Default.Analyzers.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add member to abstraction..
        /// </summary>
        internal static string AdapterAddMemberDescription {
            get {
                return ResourceManager.GetString("AdapterAddMemberDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add member {0} to abstraction {1}.
        /// </summary>
        internal static string AdapterAddMemberMessageFormat {
            get {
                return ResourceManager.GetString("AdapterAddMemberMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add member to abstraction.
        /// </summary>
        internal static string AdapterAddMemberTitle {
            get {
                return ResourceManager.GetString("AdapterAddMemberTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call factory method..
        /// </summary>
        internal static string AdapterCallFactoryDescription {
            get {
                return ResourceManager.GetString("AdapterCallFactoryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call factory method to convert {0} to {1}.
        /// </summary>
        internal static string AdapterCallFactoryMessageFormat {
            get {
                return ResourceManager.GetString("AdapterCallFactoryMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call factory method.
        /// </summary>
        internal static string AdapterCallFactoryTitle {
            get {
                return ResourceManager.GetString("AdapterCallFactoryTitle", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Refactor usage to another type..
        /// </summary>
        internal static string AdapterDefinitionDescription {
            get {
                return ResourceManager.GetString("AdapterDefinitionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refactor usage of type {0} to {1}.
        /// </summary>
        internal static string AdapterDefinitionMessageFormat {
            get {
                return ResourceManager.GetString("AdapterDefinitionMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refactor usage of type to another type.
        /// </summary>
        internal static string AdapterDefinitionTitle {
            get {
                return ResourceManager.GetString("AdapterDefinitionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter types must be attributes..
        /// </summary>
        internal static string AdapterDescriptorTypeAttributeDescription {
            get {
                return ResourceManager.GetString("AdapterDescriptorTypeAttributeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter type {0} must derive from attribute.
        /// </summary>
        internal static string AdapterDescriptorTypeAttributeMessageFormat {
            get {
                return ResourceManager.GetString("AdapterDescriptorTypeAttributeMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter types must be attributes.
        /// </summary>
        internal static string AdapterDescriptorTypeAttributeTitle {
            get {
                return ResourceManager.GetString("AdapterDescriptorTypeAttributeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter types must have correct constructor count..
        /// </summary>
        internal static string AdapterDescriptorTypeConstructorCountDescription {
            get {
                return ResourceManager.GetString("AdapterDescriptorTypeConstructorCountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter type {0} should only have {1} constructor(s).
        /// </summary>
        internal static string AdapterDescriptorTypeConstructorCountMessageFormat {
            get {
                return ResourceManager.GetString("AdapterDescriptorTypeConstructorCountMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter types must have correct constructor count.
        /// </summary>
        internal static string AdapterDescriptorTypeConstructorCountTitle {
            get {
                return ResourceManager.GetString("AdapterDescriptorTypeConstructorCountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter attribute constructors must have correct parameter count..
        /// </summary>
        internal static string AdapterDescriptorTypeParameterCountDescription {
            get {
                return ResourceManager.GetString("AdapterDescriptorTypeParameterCountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter attribute {0} constructor must have {1} parameter(s).
        /// </summary>
        internal static string AdapterDescriptorTypeParameterCountMessageFormat {
            get {
                return ResourceManager.GetString("AdapterDescriptorTypeParameterCountMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter attribute constructors must have correct parameter count.
        /// </summary>
        internal static string AdapterDescriptorTypeParameterCountTitle {
            get {
                return ResourceManager.GetString("AdapterDescriptorTypeParameterCountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter attributes must have correct constructor parameter..
        /// </summary>
        internal static string AdapterDescriptorTypeParameterDescription {
            get {
                return ResourceManager.GetString("AdapterDescriptorTypeParameterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter attribute {0} parameter should be of type {1}.
        /// </summary>
        internal static string AdapterDescriptorTypeParameterMessageFormat {
            get {
                return ResourceManager.GetString("AdapterDescriptorTypeParameterMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter attributes must have correct constructor parameter.
        /// </summary>
        internal static string AdapterDescriptorTypeParameterTitle {
            get {
                return ResourceManager.GetString("AdapterDescriptorTypeParameterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter factory method must be static..
        /// </summary>
        internal static string AdapterFactoryMustBeStaticDescription {
            get {
                return ResourceManager.GetString("AdapterFactoryMustBeStaticDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter factory method {0} must be static.
        /// </summary>
        internal static string AdapterFactoryMustBeStaticMessageFormat {
            get {
                return ResourceManager.GetString("AdapterFactoryMustBeStaticMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter factory method must be static.
        /// </summary>
        internal static string AdapterFactoryMustBeStaticTitle {
            get {
                return ResourceManager.GetString("AdapterFactoryMustBeStaticTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified adapter factory must exist..
        /// </summary>
        internal static string AdapterFactoryMustExistDescription {
            get {
                return ResourceManager.GetString("AdapterFactoryMustExistDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified adapter factory method {0} on type {1} does not exist.
        /// </summary>
        internal static string AdapterFactoryMustExistMessageFormat {
            get {
                return ResourceManager.GetString("AdapterFactoryMustExistMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified adapter factory must exist.
        /// </summary>
        internal static string AdapterFactoryMustExistTitle {
            get {
                return ResourceManager.GetString("AdapterFactoryMustExistTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refactor usage to another type..
        /// </summary>
        internal static string AdapterRefactorDescription {
            get {
                return ResourceManager.GetString("AdapterRefactorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refactor usage of type {0} to {1}.
        /// </summary>
        internal static string AdapterRefactorMessageFormat {
            get {
                return ResourceManager.GetString("AdapterRefactorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refactor usage of type to another type.
        /// </summary>
        internal static string AdapterRefactorTitle {
            get {
                return ResourceManager.GetString("AdapterRefactorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This type is not supported on .NET Core/.NET 5+ and should be replaced with a modern equivalent..
        /// </summary>
        internal static string ApiAlertGenericDescription {
            get {
                return ResourceManager.GetString("ApiAlertGenericDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string ApiAlertGenericMessageFormat {
            get {
                return ResourceManager.GetString("ApiAlertGenericMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace unsupported API.
        /// </summary>
        internal static string ApiAlertGenericTitle {
            get {
                return ResourceManager.GetString("ApiAlertGenericTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This attribute type is not supported on .NET Core/.NET 5+ and should be replaced with a modern equivalent..
        /// </summary>
        internal static string AttributeUpgradeDescription {
            get {
                return ResourceManager.GetString("AttributeUpgradeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute type &apos;{0}&apos; should be replaced with &apos;{1}&apos;.
        /// </summary>
        internal static string AttributeUpgradeMessageFormat {
            get {
                return ResourceManager.GetString("AttributeUpgradeMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes should be upgraded.
        /// </summary>
        internal static string AttributeUpgradeTitle {
            get {
                return ResourceManager.GetString("AttributeUpgradeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;UnsafeDeserialize()&apos; should be replaced with &apos;Deserialize()&apos;..
        /// </summary>
        internal static string BinaryFormatterUnsafeDeserializeDescription {
            get {
                return ResourceManager.GetString("BinaryFormatterUnsafeDeserializeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;UnsafeDeserialize()&apos; should be replaced with &apos;Deserialize()&apos;.
        /// </summary>
        internal static string BinaryFormatterUnsafeDeserializeMessageFormat {
            get {
                return ResourceManager.GetString("BinaryFormatterUnsafeDeserializeMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;UnsafeDeserialize()&apos; does not exist.
        /// </summary>
        internal static string BinaryFormatterUnsafeDeserializeTitle {
            get {
                return ResourceManager.GetString("BinaryFormatterUnsafeDeserializeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter-related types should come from the Microsoft.AspNetCore.Mvc.Filters namespace in ASP.NET Core..
        /// </summary>
        internal static string FilterDescription {
            get {
                return ResourceManager.GetString("FilterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier &apos;{0}&apos; should be replaced with &apos;{1}&apos;.
        /// </summary>
        internal static string FilterMessageFormat {
            get {
                return ResourceManager.GetString("FilterMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter types should be used from the Microsoft.AspNetCore.Mvc.Filters namespace.
        /// </summary>
        internal static string FilterTitle {
            get {
                return ResourceManager.GetString("FilterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HelperResult should be replaced with Microsoft.AspNetCore.Mvc.Razor.HelperResult..
        /// </summary>
        internal static string HelperResultDescription {
            get {
                return ResourceManager.GetString("HelperResultDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier &apos;{0}&apos; should be replaced with &apos;{1}&apos;.
        /// </summary>
        internal static string HelperResultMessageFormat {
            get {
                return ResourceManager.GetString("HelperResultMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HelperResult should be replaced with Microsoft.AspNetCore.Mvc.Razor.HelperResult.
        /// </summary>
        internal static string HelperResultTitle {
            get {
                return ResourceManager.GetString("HelperResultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HtmlHelper should be replaced with Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper or Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper..
        /// </summary>
        internal static string HtmlHelperDescription {
            get {
                return ResourceManager.GetString("HtmlHelperDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier &apos;{0}&apos; should be replaced with &apos;{1}&apos;.
        /// </summary>
        internal static string HtmlHelperMessageFormat {
            get {
                return ResourceManager.GetString("HtmlHelperMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HtmlHelper should be replaced with IHtmlHelper.
        /// </summary>
        internal static string HtmlHelperTitle {
            get {
                return ResourceManager.GetString("HtmlHelperTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HtmlString, IHtmlString, and MvcHtmlString types should be replaced with Microsoft.AspNetCore.Html.HtmlString..
        /// </summary>
        internal static string HtmlStringDescription {
            get {
                return ResourceManager.GetString("HtmlStringDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier &apos;{0}&apos; should be replaced with Microsoft.AspNetCore.Html.HtmlString.
        /// </summary>
        internal static string HtmlStringMessageFormat {
            get {
                return ResourceManager.GetString("HtmlStringMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HtmlString types should be replaced with Microsoft.AspNetCore.Html.HtmlString.
        /// </summary>
        internal static string HtmlStringTitle {
            get {
                return ResourceManager.GetString("HtmlStringTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HttpContext does not have a Current property; get the context from a controller or use HttpContextAccessor instead..
        /// </summary>
        internal static string HttpContextCurrentDescription {
            get {
                return ResourceManager.GetString("HttpContextCurrentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HttpContext does not have a Current property; get the context from a controller or use HttpContextAccessor instead.
        /// </summary>
        internal static string HttpContextCurrentMessageFormat {
            get {
                return ResourceManager.GetString("HttpContextCurrentMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not use HttpContext.Current.
        /// </summary>
        internal static string HttpContextCurrentTitle {
            get {
                return ResourceManager.GetString("HttpContextCurrentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HttpContext.DebuggerEnabled does not exist in ASP.NET Core and should be replaced with System.Diagnostics.Debugger.IsAttached..
        /// </summary>
        internal static string HttpContextDebuggingEnabledDescription {
            get {
                return ResourceManager.GetString("HttpContextDebuggingEnabledDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HttpContext.DebuggerEnabled should be replaced with System.Diagnostics.Debugger.IsAttached.
        /// </summary>
        internal static string HttpContextDebuggingEnabledMessageFormat {
            get {
                return ResourceManager.GetString("HttpContextDebuggingEnabledMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HttpContext.DebuggerEnabled should be replaced with System.Diagnostics.Debugger.IsAttached.
        /// </summary>
        internal static string HttpContextDebuggingEnabledTitle {
            get {
                return ResourceManager.GetString("HttpContextDebuggingEnabledTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionResult types should come from the Microsoft.AspNetCore.Mvc namespace in ASP.NET Core..
        /// </summary>
        internal static string ResultTypeDescription {
            get {
                return ResourceManager.GetString("ResultTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier &apos;{0}&apos; should be replaced with &apos;{1}&apos;.
        /// </summary>
        internal static string ResultTypeMessageFormat {
            get {
                return ResourceManager.GetString("ResultTypeMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionResult types should come from the Microsoft.AspNetCore.Mvc namespace.
        /// </summary>
        internal static string ResultTypeTitle {
            get {
                return ResourceManager.GetString("ResultTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This type is not supported on .NET Core/.NET 5+ and should be replaced with a modern equivalent..
        /// </summary>
        internal static string TypeUpgradeDescription {
            get {
                return ResourceManager.GetString("TypeUpgradeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; should be replaced with &apos;{1}&apos;.
        /// </summary>
        internal static string TypeUpgradeMessageFormat {
            get {
                return ResourceManager.GetString("TypeUpgradeMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types should be upgraded.
        /// </summary>
        internal static string TypeUpgradeTitle {
            get {
                return ResourceManager.GetString("TypeUpgradeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UrlHelper should be replaced with Microsoft.AspNetCore.Mvc.IUrlHelper or Microsoft.AspNetCore.Mvc.Routing.UrlHelper..
        /// </summary>
        internal static string UrlHelperDescription {
            get {
                return ResourceManager.GetString("UrlHelperDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier &apos;{0}&apos; should be replaced with &apos;{1}&apos;.
        /// </summary>
        internal static string UrlHelperMessageFormat {
            get {
                return ResourceManager.GetString("UrlHelperMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UrlHelper should be replaced with IUrlHelper.
        /// </summary>
        internal static string UrlHelperTitle {
            get {
                return ResourceManager.GetString("UrlHelperTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Deployment is not supported on .NET Core.
        /// </summary>
        internal static string UsingSystemDeployment {
            get {
                return ResourceManager.GetString("UsingSystemDeployment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Deployment is not supported on .NET Core..
        /// </summary>
        internal static string UsingSystemDeploymentDescription {
            get {
                return ResourceManager.GetString("UsingSystemDeploymentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASP.NET Core projects should not reference System.Web or OWIN namespaces..
        /// </summary>
        internal static string UsingSystemWebDescription {
            get {
                return ResourceManager.GetString("UsingSystemWebDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace &apos;{0}&apos; should not be referenced in ASP.NET Core projects.
        /// </summary>
        internal static string UsingSystemWebMessageFormat {
            get {
                return ResourceManager.GetString("UsingSystemWebMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASP.NET Core projects should not reference ASP.NET namespaces.
        /// </summary>
        internal static string UsingSystemWebTitle {
            get {
                return ResourceManager.GetString("UsingSystemWebTitle", resourceCulture);
            }
        }
    }
}
