//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.DotNet.UpgradeAssistant.DeprecatedApisAnalyzer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.DotNet.UpgradeAssistant.DeprecatedApisAnalyzer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add member to abstraction..
        /// </summary>
        internal static string AdapterAddMemberDescription {
            get {
                return ResourceManager.GetString("AdapterAddMemberDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add member {0} to abstraction {1}.
        /// </summary>
        internal static string AdapterAddMemberMessageFormat {
            get {
                return ResourceManager.GetString("AdapterAddMemberMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add member to abstraction.
        /// </summary>
        internal static string AdapterAddMemberTitle {
            get {
                return ResourceManager.GetString("AdapterAddMemberTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call factory method..
        /// </summary>
        internal static string AdapterCallFactoryDescription {
            get {
                return ResourceManager.GetString("AdapterCallFactoryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call factory method to convert {0} to {1}.
        /// </summary>
        internal static string AdapterCallFactoryMessageFormat {
            get {
                return ResourceManager.GetString("AdapterCallFactoryMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call factory method.
        /// </summary>
        internal static string AdapterCallFactoryTitle {
            get {
                return ResourceManager.GetString("AdapterCallFactoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter definition..
        /// </summary>
        internal static string AdapterDefinitionDescription {
            get {
                return ResourceManager.GetString("AdapterDefinitionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter definition for {0}.
        /// </summary>
        internal static string AdapterDefinitionMessageFormat {
            get {
                return ResourceManager.GetString("AdapterDefinitionMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter definition.
        /// </summary>
        internal static string AdapterDefinitionTitle {
            get {
                return ResourceManager.GetString("AdapterDefinitionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter types must be attributes..
        /// </summary>
        internal static string AdapterDescriptorTypeAttributeDescription {
            get {
                return ResourceManager.GetString("AdapterDescriptorTypeAttributeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter type {0} must derive from attribute.
        /// </summary>
        internal static string AdapterDescriptorTypeAttributeMessageFormat {
            get {
                return ResourceManager.GetString("AdapterDescriptorTypeAttributeMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter types must be attributes.
        /// </summary>
        internal static string AdapterDescriptorTypeAttributeTitle {
            get {
                return ResourceManager.GetString("AdapterDescriptorTypeAttributeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter types must have correct constructor count..
        /// </summary>
        internal static string AdapterDescriptorTypeConstructorCountDescription {
            get {
                return ResourceManager.GetString("AdapterDescriptorTypeConstructorCountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter type {0} should only have {1} constructor(s).
        /// </summary>
        internal static string AdapterDescriptorTypeConstructorCountMessageFormat {
            get {
                return ResourceManager.GetString("AdapterDescriptorTypeConstructorCountMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter types must have correct constructor count.
        /// </summary>
        internal static string AdapterDescriptorTypeConstructorCountTitle {
            get {
                return ResourceManager.GetString("AdapterDescriptorTypeConstructorCountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter attribute constructors must have correct parameter count..
        /// </summary>
        internal static string AdapterDescriptorTypeParameterCountDescription {
            get {
                return ResourceManager.GetString("AdapterDescriptorTypeParameterCountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter attribute {0} constructor must have {1} parameter(s).
        /// </summary>
        internal static string AdapterDescriptorTypeParameterCountMessageFormat {
            get {
                return ResourceManager.GetString("AdapterDescriptorTypeParameterCountMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter attribute constructors must have correct parameter count.
        /// </summary>
        internal static string AdapterDescriptorTypeParameterCountTitle {
            get {
                return ResourceManager.GetString("AdapterDescriptorTypeParameterCountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter attributes must have correct constructor parameter..
        /// </summary>
        internal static string AdapterDescriptorTypeParameterDescription {
            get {
                return ResourceManager.GetString("AdapterDescriptorTypeParameterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter attribute {0} parameter should be of type {1}.
        /// </summary>
        internal static string AdapterDescriptorTypeParameterMessageFormat {
            get {
                return ResourceManager.GetString("AdapterDescriptorTypeParameterMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter attributes must have correct constructor parameter.
        /// </summary>
        internal static string AdapterDescriptorTypeParameterTitle {
            get {
                return ResourceManager.GetString("AdapterDescriptorTypeParameterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter factory method must be static..
        /// </summary>
        internal static string AdapterFactoryMustBeStaticDescription {
            get {
                return ResourceManager.GetString("AdapterFactoryMustBeStaticDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter factory method {0} must be static.
        /// </summary>
        internal static string AdapterFactoryMustBeStaticMessageFormat {
            get {
                return ResourceManager.GetString("AdapterFactoryMustBeStaticMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter factory method must be static.
        /// </summary>
        internal static string AdapterFactoryMustBeStaticTitle {
            get {
                return ResourceManager.GetString("AdapterFactoryMustBeStaticTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified adapter factory must exist..
        /// </summary>
        internal static string AdapterFactoryMustExistDescription {
            get {
                return ResourceManager.GetString("AdapterFactoryMustExistDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified adapter factory method {0} on type {1} does not exist.
        /// </summary>
        internal static string AdapterFactoryMustExistMessageFormat {
            get {
                return ResourceManager.GetString("AdapterFactoryMustExistMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified adapter factory must exist.
        /// </summary>
        internal static string AdapterFactoryMustExistTitle {
            get {
                return ResourceManager.GetString("AdapterFactoryMustExistTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refactor usage to another type..
        /// </summary>
        internal static string AdapterRefactorDescription {
            get {
                return ResourceManager.GetString("AdapterRefactorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refactor usage of type {0} to {1}.
        /// </summary>
        internal static string AdapterRefactorMessageFormat {
            get {
                return ResourceManager.GetString("AdapterRefactorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refactor usage of type to another type.
        /// </summary>
        internal static string AdapterRefactorTitle {
            get {
                return ResourceManager.GetString("AdapterRefactorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirect static member access to alternate member..
        /// </summary>
        internal static string AdapterStaticMemberDescription {
            get {
                return ResourceManager.GetString("AdapterStaticMemberDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change call from {0} to {1}.
        /// </summary>
        internal static string AdapterStaticMemberMessageFormat {
            get {
                return ResourceManager.GetString("AdapterStaticMemberMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirect static member access to alternate member.
        /// </summary>
        internal static string AdapterStaticMemberTitle {
            get {
                return ResourceManager.GetString("AdapterStaticMemberTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an adapter descriptor to facilitate migrations away from this type..
        /// </summary>
        internal static string AddAdapterDescriptorDescription {
            get {
                return ResourceManager.GetString("AddAdapterDescriptorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an adapter descriptor for &apos;{0}&apos;.
        /// </summary>
        internal static string AddAdapterDescriptorMessageFormat {
            get {
                return ResourceManager.GetString("AddAdapterDescriptorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an adapter descriptor to facilitate migrations away from this type.
        /// </summary>
        internal static string AddAdapterDescriptorTitle {
            get {
                return ResourceManager.GetString("AddAdapterDescriptorTitle", resourceCulture);
            }
        }
    }
}
