//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.DotNet.UpgradeAssistant.Extensions.Maui {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.DotNet.UpgradeAssistant.Extensions.Maui.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Xamarin.Forms namespace.
        /// </summary>
        internal static string NamespaceXamarinFormsTitle {
            get {
                return ResourceManager.GetString("NamespaceXamarinFormsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace &apos;{0}&apos; should not be referenced in .NET MAUI projects.
        /// </summary>
        internal static string UsingXamarinEssentialsAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("UsingXamarinEssentialsAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET MAUI projects should not reference Xamarin.Essentials namespaces.
        /// </summary>
        internal static string UsingXamarinEssentialsAnalyzerTitle {
            get {
                return ResourceManager.GetString("UsingXamarinEssentialsAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This using directive is not supported on .NET MAUI and should be replaced..
        /// </summary>
        internal static string UsingXamarinEssentialsDescription {
            get {
                return ResourceManager.GetString("UsingXamarinEssentialsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace using directive.
        /// </summary>
        internal static string UsingXamarinEssentialsTitle {
            get {
                return ResourceManager.GetString("UsingXamarinEssentialsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This using directive is not supported on .NET MAUI and should be replaced..
        /// </summary>
        internal static string UsingXamarinFormsAnalyzerDescription {
            get {
                return ResourceManager.GetString("UsingXamarinFormsAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace &apos;{0}&apos; should not be referenced in .NET MAUI projects.
        /// </summary>
        internal static string UsingXamarinFormsAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("UsingXamarinFormsAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET MAUI projects should not reference Xamarin.Forms namespaces.
        /// </summary>
        internal static string UsingXamarinFormsAnalyzerTitle {
            get {
                return ResourceManager.GetString("UsingXamarinFormsAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace using directive.
        /// </summary>
        internal static string UsingXamarinFormsTitle {
            get {
                return ResourceManager.GetString("UsingXamarinFormsTitle", resourceCulture);
            }
        }
    }
}
