//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.DotNet.UpgradeAssistant.Cli {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.DotNet.UpgradeAssistant.Cli.LocalizedStrings", typeof(LocalizedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding extension {Name} from {Source}.
        /// </summary>
        internal static string AddExtensionDetails {
            get {
                return ResourceManager.GetString("AddExtensionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find extension {Name} from {Source}.
        /// </summary>
        internal static string AddExtensionFailed {
            get {
                return ResourceManager.GetString("AddExtensionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added extension {Name} from {Source}.
        /// </summary>
        internal static string AddExtensionSuccess {
            get {
                return ResourceManager.GetString("AddExtensionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of extension.
        /// </summary>
        internal static string ExtensionManagementName {
            get {
                return ResourceManager.GetString("ExtensionManagementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source of extension.
        /// </summary>
        internal static string ExtensionManagementSource {
            get {
                return ResourceManager.GetString("ExtensionManagementSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version of extension.
        /// </summary>
        internal static string ExtensionManagementVersion {
            get {
                return ResourceManager.GetString("ExtensionManagementVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current extensions:.
        /// </summary>
        internal static string ListExtensionDetails {
            get {
                return ResourceManager.GetString("ListExtensionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name}: {Source}.
        /// </summary>
        internal static string ListExtensionItem {
            get {
                return ResourceManager.GetString("ListExtensionItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing extension &apos;{Name}&apos;.
        /// </summary>
        internal static string RemovingExtension {
            get {
                return ResourceManager.GetString("RemovingExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not remove extension &apos;{Name}&apos;.
        /// </summary>
        internal static string RemovingExtensionFailed {
            get {
                return ResourceManager.GetString("RemovingExtensionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for updates for {Name}.
        /// </summary>
        internal static string UpdateExtensionDetails {
            get {
                return ResourceManager.GetString("UpdateExtensionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find an update for extension {Name}.
        /// </summary>
        internal static string UpdateExtensionFailed {
            get {
                return ResourceManager.GetString("UpdateExtensionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found an update for {Name} to {Version}.
        /// </summary>
        internal static string UpdateExtensionSuccess {
            get {
                return ResourceManager.GetString("UpdateExtensionSuccess", resourceCulture);
            }
        }
    }
}
