//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.DotNet.UpgradeAssistant.Extensions.BinaryAnalysis {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.DotNet.UpgradeAssistant.Extensions.BinaryAnalysis.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0} Availability: {1}].
        /// </summary>
        internal static string BinaryAnalysisApiAvailabilityFormatMessageFormat {
            get {
                return ResourceManager.GetString("BinaryAnalysisApiAvailabilityFormatMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Available via external Package.
        /// </summary>
        internal static string BinaryAnalysisApiAvailableExternalPackageRuleName {
            get {
                return ResourceManager.GetString("BinaryAnalysisApiAvailableExternalPackageRuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Obsoleted].
        /// </summary>
        internal static string BinaryAnalysisApiObsoletedMessage {
            get {
                return ResourceManager.GetString("BinaryAnalysisApiObsoletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API has been obsoleted in target framework.
        /// </summary>
        internal static string BinaryAnalysisApiObsoletedRuleName {
            get {
                return ResourceManager.GetString("BinaryAnalysisApiObsoletedRuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Version: {0}].
        /// </summary>
        internal static string BinaryAnalysisApiPackageVersionMessageFormat {
            get {
                return ResourceManager.GetString("BinaryAnalysisApiPackageVersionMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API is unsupported in target platform.
        /// </summary>
        internal static string BinaryAnalysisApiUnsupportedPlatformRuleName {
            get {
                return ResourceManager.GetString("BinaryAnalysisApiUnsupportedPlatformRuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Unavailable in target framework.
        /// </summary>
        internal static string BinaryAnalysisAssemblyNotAvailableRuleName {
            get {
                return ResourceManager.GetString("BinaryAnalysisAssemblyNotAvailableRuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid .NET assembly.
        /// </summary>
        internal static string BinaryAnalysisInvalidAssemblyMessage {
            get {
                return ResourceManager.GetString("BinaryAnalysisInvalidAssemblyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member {0}.{1}.{2}.
        /// </summary>
        internal static string BinaryAnalysisMemberQualifierFormat {
            get {
                return ResourceManager.GetString("BinaryAnalysisMemberQualifierFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace {0}.
        /// </summary>
        internal static string BinaryAnalysisNamespaceQualifierFormat {
            get {
                return ResourceManager.GetString("BinaryAnalysisNamespaceQualifierFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0} Unsupported].
        /// </summary>
        internal static string BinaryAnalysisPackageUnsupportedPlatformMessageFormat {
            get {
                return ResourceManager.GetString("BinaryAnalysisPackageUnsupportedPlatformMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processed {0}....
        /// </summary>
        internal static string BinaryAnalysisProcessedAssemblyMessageFormat {
            get {
                return ResourceManager.GetString("BinaryAnalysisProcessedAssemblyMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0}.{1}.
        /// </summary>
        internal static string BinaryAnalysisTypeQualifierFormat {
            get {
                return ResourceManager.GetString("BinaryAnalysisTypeQualifierFormat", resourceCulture);
            }
        }
    }
}
