name: "Auto-assign Opened PRs to UA Project 'Dev in progress' column"

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  Add_New_Issue_To_Project:
    runs-on: ubuntu-latest
    steps:
    - uses: konradpabjan/actions-add-new-issue-to-column@v1.1
      with:
        action-token: "${{ secrets.ACTIONS_PAT }}"
        project-url: 'https://github.com/orgs/dotnet/projects/108'
        column-name: 'Dev In Progress'
