name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      reason_to_run:
        description: 'Reason to run'
        required: true

env:
  buildConfiguration: Release

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Reason
      if: github.event.inputs.reason_to_run
      run: echo "${{ github.event.inputs.reason_to_run }}"
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 3.1.x
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2
    - name: Update version
      run: |
        dotnet tool install --global GitVersion.Tool
        dotnet gitversion /output buildserver /nofetch
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: ./build.bat -ci -c ${{ env.buildConfiguration }} /p:OfficialBuild=true
    - name: Test
      run: dotnet test -c ${{ env.buildConfiguration }}
    - name: Publish Packages
      uses: actions/upload-artifact@v2
      with:
          name: tools
          path: artifacts/packages/Release/Shipping/*

